# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- '*'

variables:
    dotnetSdkVersion: '6.x'

pool:
     vmImage: 'windows-latest'
    
steps:
    - task: UseDotNet@2
        
    inputs:
       version: '$(dotnetSdkVersion)'

    - powershell: ./build.ps1
      displayname: 'Execute Cake PowerShell Bootstrapper'
    
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
       summaryFileLocation: $(System.DefaultWorkingDirectory)/Calculator.Test/TestResults**/coverage.cobertura.xml

