# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- '*'

variables:
    dotnetSdkVersion: '6.x'

pool:
     vmImage: 'windows-latest'
    

steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install -g dotnet-format --ignore-failed-sources'

    - task: PowerShell@2
      inputs:
        filePath: 'build.ps1'
        args: '--target=Build'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(System.DefaultWorkingDirectory)/Calculator.Test/TestResults**/coverage.cobertura.xml

